import { IPage } from "./IPage";
import { ITodoListUser } from "./ITodoListUser";

/**
 * Paginated container for user entities. Returned in multi-user
 * administration/list queries.
 *
 * Strictly contains pagination metadata and user array.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListUser = {
  /** Page information (current, limit, records, pages). */
  pagination: IPage.IPagination;

  /** Array of user entities on this page. */
  data: ITodoListUser[];
};
export namespace IPageITodoListUser {
  /**
   * Paginated set of summary user data, suitable for session lists, access
   * logs, and lightweight user panels.
   *
   * Contains only safe summary info.
   */
  export type ISummary = {
    /** Pagination context. */
    pagination: IPage.IPagination;

    /** Summary user array data. */
    data: ITodoListUser.ISummary[];
  };
}
