import { IPage } from "./IPage";
import { ITodoListDeletedTodoLog } from "./ITodoListDeletedTodoLog";

/**
 * Paginated collection of deleted todo logs. Wraps array of audit log resources
 * in a list display format with pagination and navigation support. Used by all
 * endpoints returning multi-record result sets for deleted todo audit/history
 * operations.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListDeletedTodoLog = {
  /**
   * Pagination state information for the current result set of deleted todo
   * logs. Includes page, per-page limit, record and page totals as required
   * by standard pagination schema.
   */
  pagination: IPage.IPagination;

  /**
   * Array of deleted todo log records, each representing an audit snapshot of
   * a formerly active todo at time of deletion.
   */
  data: ITodoListDeletedTodoLog[];
};
