import { IPage } from "./IPage";
import { ITodoListTodo } from "./ITodoListTodo";

/**
 * Paginated result schema for detailed todo list API. Contains full todo entity
 * records in data array, along with pagination context (page/current/total).
 *
 * Used only where detailed full-entity lists are appropriate, e.g., admin
 * workspace or full-edit workflow.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListTodo = {
  /** Page context: page, limit, records, pages. */
  pagination: IPage.IPagination;

  /** Array of todo entity records. */
  data: ITodoListTodo[];
};
export namespace IPageITodoListTodo {
  /**
   * Paginated response for todo item summaries. Contains both metadata about
   * query position (pagination details) and the list of user's todos matching
   * the current filter/sort. Suitable for paged navigation and client-side
   * rendering of list views.
   */
  export type ISummary = {
    /**
     * Pagination metadata describing the current result set, page position,
     * total records, and navigation cues. Required in all paginated
     * responses.
     */
    pagination: IPage.IPagination;

    /**
     * Array of todo summary objects in this paginated page. Each entry is a
     * summary representation of a user's todo for fast list views.
     */
    data: ITodoListTodo.ISummary[];
  };
}
