import { tags } from "typia";

/**
 * Core audit log entity component, representing a single admin action on a
 * user's todo (view or delete). All fields map directly to the
 * todo_list_audit_logs table. Used for compliance, business monitoring, and
 * security reviews.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoListAuditLog = {
  /**
   * Unique identifier for this audit log entry (matches id column in
   * todo_list_audit_logs table).
   */
  id: string & tags.Format<"uuid">;

  /** ID of the admin who performed the action (FK to todo_list_admins). */
  todo_list_admin_id: string & tags.Format<"uuid">;

  /** ID of the user whose todo was affected (FK to todo_list_users). */
  todo_list_user_id: string & tags.Format<"uuid">;

  /** ID of the todo item affected (FK to todo_list_todos). */
  todo_list_todo_id: string & tags.Format<"uuid">;

  /**
   * The type of admin action on the todo—either 'view' or 'delete'; as
   * defined in business rules and schema.
   */
  action: "view" | "delete";

  /**
   * Optional free-form explanation or business rationale for the action; may
   * be null or empty if not supplied.
   */
  rationale?: string | null | undefined;

  /** Timestamp for when the audit log was created (audit trail). */
  created_at: string & tags.Format<"date-time">;
};
export namespace ITodoListAuditLog {
  /**
   * Filtering and pagination input for audit log searching. All fields are
   * optional and mutually combinable. Supports robust admin/operational
   * compliance search as described in business requirements.
   */
  export type IRequest = {
    /**
     * Optional filter by acting admin id (uuid). Only audit logs matching
     * this admin will be included if provided. Null or omitted means no
     * filter.
     */
    todo_list_admin_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional filter by user id (uuid); selects logs associated with
     * actions against this user. Null/omitted means any user.
     */
    todo_list_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional filter by todo id; restricts listing to actions on a
     * specific todo. Null/omitted = no filter.
     */
    todo_list_todo_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional filter for action type; "view" or "delete". Null/omitted
     * means any action.
     */
    action?: "view" | "delete" | null | undefined;

    /**
     * Optional substring or keyword for rationale text filtering. Null or
     * omitted disables content search.
     */
    rationale?: string | null | undefined;

    /**
     * Optional filter for audit logs created at or after this ISO
     * date-time. Null means no lower bound.
     */
    from?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Optional filter for audit logs created before or at this ISO
     * date-time. Null means no upper bound.
     */
    to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Optional page number for pagination (1 = first). Default is 1. */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Optional per-page limit (max 100). Default is 20. */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Optional sort field. Typical values: created_at (default), action,
     * admin/user ids. Null or omitted defaults to descending by
     * created_at.
     */
    sort?:
      | "created_at"
      | "action"
      | "todo_list_admin_id"
      | "todo_list_user_id"
      | "todo_list_todo_id"
      | null
      | undefined;

    /**
     * Sort direction: "asc" for ascending, "desc" for descending;
     * null/omitted for default ('desc').
     */
    direction?: "asc" | "desc" | null | undefined;
  };

  /**
   * Summary record for a single admin audit log entry. Used in
   * filters/searches on audit_log lists. Includes all core references for
   * tracking which admin did what, to which user/todo, for what action (with
   * optional rationale). Pulled from todo_list_audit_logs schema, ensuring
   * full traceability for compliance without exposing unrelated or sensitive
   * records.
   */
  export type ISummary = {
    /**
     * Primary key for this audit log record (todo_list_audit_logs.id).
     * Unique identifier for finding this row in logs and audit trails.
     */
    id: string & tags.Format<"uuid">;

    /**
     * ID (UUID) of admin account who performed the action. Reference to
     * todo_list_admins.id. Used for cross-linking between audit log and
     * admin records.
     */
    todo_list_admin_id: string & tags.Format<"uuid">;

    /**
     * ID (UUID) of the user whose todo was targeted. Reference:
     * todo_list_users.id. Ensures traceability to the individual whose data
     * was affected.
     */
    todo_list_user_id: string & tags.Format<"uuid">;

    /**
     * ID (UUID) of the todo item upon which the admin acted. Reference:
     * todo_list_todos.id. Enables tracing the target of the admin action.
     */
    todo_list_todo_id: string & tags.Format<"uuid">;

    /**
     * Admin action performed on the todo. Enum values: 'view' (admin viewed
     * todo), 'delete' (admin deleted todo). Business rule: Only these
     * actions are allowed in the schema for audit logging purposes.
     */
    action: "view" | "delete";

    /**
     * Optional explanation entered by the admin justifying this action.
     * Free text (nullable). Useful for compliance review. Reference:
     * todo_list_audit_logs.rationale.
     */
    rationale?: string | null | undefined;

    /**
     * Timestamp when this admin action occurred (ISO 8601 UTC). Reference:
     * todo_list_audit_logs.created_at.
     */
    created_at: string & tags.Format<"date-time">;
  };
}
