import { tags } from "typia";

/**
 * Active session records for user authentication in the Todo List app.
 *
 * This entity stores per-session issued tokens, audit metadata (user agent, IP
 * address), timestamps, and session status fields. Used for login audit, global
 * logout, and active session tracking.
 *
 * Sensitive session tokens are never exposed on client APIs outside of
 * controlled authentication responses.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoListAuthSession = {
  /** Session ID (UUID) in the database. */
  id: string & tags.Format<"uuid">;

  /** Foreign key to the owning user. */
  todo_list_user_id: string & tags.Format<"uuid">;

  /** Opaque authentication token for this session (JWT, etc.). */
  session_token: string;

  /** User agent string (browser/device/OS details) for the session. */
  user_agent?: string | null;

  /** IP address (if captured under privacy rules), for audit only. */
  ip_address?: string | null;

  /** Session expiration timestamp. */
  expires_at: string & tags.Format<"date-time">;

  /** Timestamp when the session was established. */
  created_at: string & tags.Format<"date-time">;

  /** When / if this session was revoked, or null if active. */
  revoked_at?: (string & tags.Format<"date-time">) | null;
};
