import { tags } from "typia";

/**
 * Audit log entry for a deleted todo. Captures a complete business snapshot of
 * the todo at time of permanent deletion, including all user-facing and
 * compliance tracking fields from the source record. Used for audit reporting,
 * user history view, and retention window enforcement. Never includes
 * relational identity fields or security-sensitive information (passwords,
 * owner id, etc.).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoListDeletedTodoLog = {
  /**
   * Unique identifier for the deleted todo log/audit entry. Assigned on todo
   * deletion. Always globally unique and persistently references the audit
   * record for the deletion event.
   */
  id: string & tags.Format<"uuid">;

  /**
   * The ID of the original todo item prior to deletion. This UUID uniquely
   * ties the log record back to the historical instance. Cannot collide with
   * any active or former todo ID for user audit traceability.
   */
  original_todo_id: string & tags.Format<"uuid">;

  /**
   * Title of the deleted todo at the time of deletion. Maximum 255
   * characters. Sourced directly from the historical record prior to
   * deletion. Must not be empty according to business rules imposed on active
   * todos.
   */
  title: string & tags.MaxLength<255>;

  /**
   * (Optional) Description field captured at time of deletion. Copied from
   * transient field and may be empty or omitted.
   */
  description?: string & tags.MaxLength<1000>;

  /**
   * (Optional) Due date that was set at time of deletion. If unspecified,
   * null. Remains valid as an ISO 8601 date-time snapshot.
   */
  due_date?: (string & tags.Format<"date-time">) | null;

  /**
   * True if the todo was marked completed at time of deletion, else false.
   * Fiduciary snapshot for accurate audit and self-service recovery.
   */
  is_completed: boolean;

  /**
   * (Optional) Timestamp of completion, if the todo was completed before
   * deletion. ISO8601, null if never completed.
   */
  completed_at?: (string & tags.Format<"date-time">) | null;

  /**
   * Original creation timestamp of the todo (ISO 8601). Persisted as an
   * unmodifiable copy from the source table at deletion.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last 'update' timestamp of the todo, at the moment immediately prior to
   * deletion. Allows accurate post-mortem and user history review. Always in
   * ISO 8601 UTC.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp of deletion action (ISO 8601), accurately reflecting when user
   * triggered permanent removal. Used for purge logic and compliance with
   * retention period.
   */
  deleted_at: string & tags.Format<"date-time">;
};
export namespace ITodoListDeletedTodoLog {
  /**
   * Request body for retrieving a filtered, sorted, and paginated list of
   * deleted todo logs for the authenticated user. Supports pagination
   * (page/limit), date range filters, completion status filter, and partial
   * title text search. Used for audit and history views within the permitted
   * data retention window as enforced by business and legal requirements.
   */
  export type IRequest = {
    /**
     * Pagination: page number (1-based). Optional, defaults to 1. Used for
     * navigating multi-page result sets.
     */
    page?: number & tags.Type<"int32"> & tags.Minimum<1>;

    /**
     * Pagination: maximum records per page (min 1, max 100, business
     * defaults applied if omitted).
     */
    limit?: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>;

    /**
     * (Optional) Filter to deleted logs where 'deleted_at' is equal to or
     * after this ISO 8601 date-time.
     */
    deleted_since?: (string & tags.Format<"date-time">) | null;

    /**
     * (Optional) Filter to deleted logs where 'deleted_at' is equal to or
     * before this ISO 8601 date-time.
     */
    deleted_before?: (string & tags.Format<"date-time">) | null;

    /**
     * (Optional) Case-insensitive search string to match against the
     * 'title' field of deleted todos. Enables filtered navigation through
     * audit logs.
     */
    search?: string & tags.MaxLength<255>;

    /**
     * Sort criteria for the deleted log list. Accepts 'deleted_at' or
     * 'created_at'. Defaults to 'deleted_at' if omitted.
     */
    sort_by?: "deleted_at" | "created_at";

    /**
     * Sort order: 'asc' for ascending or 'desc' for descending (default:
     * 'desc' if omitted).
     */
    sort_direction?: "asc" | "desc";

    /**
     * (Optional) Filter records by completion status at deletion time.
     * True: completed, False: incomplete. Null/undefined: any status.
     */
    is_completed?: boolean;
  };
}
