import { tags } from "typia";

/**
 * Schema for single-use password reset tokens associated with a user, generated
 * on password reset request.
 *
 * Contains secure token value, expiry timestamp, and audit information. Only
 * used in password reset flows. No sensitive data is exposed outside controlled
 * flows.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoListPasswordResetToken = {
  /** Unique identifier of the password reset token. */
  id: string & tags.Format<"uuid">;

  /** User ID associated with this reset token. */
  todo_list_user_id: string & tags.Format<"uuid">;

  /** Secure, randomly generated token string. */
  token: string;

  /** Token expiration timestamp. */
  expires_at: string & tags.Format<"date-time">;

  /** Timestamp when the token was used, or null if not used. */
  used_at?: (string & tags.Format<"date-time">) | null;

  /** Time when the reset token was created. */
  created_at: string & tags.Format<"date-time">;
};
